### ISSUE TITLE
Duplicate warnings when having several templates switched by exclude/include where these contain the same Evrs

### ISSUE THREAD

**Issue by palkitt** [equinor/vscode-septic#670]
Using exclude/exclude to select which template to use for different wells. These templates contains many of the same Evrs, but only one of the (similar) templates is used for a single well. This makes a lot of duplicate warnings. 

Best solution is to neglect duplicates from one of these templates to the other. Second best is to be able to turn off a warning for sections of a template.

Example yaml file:
```
 - name: 06_DmmyApplWell.cnfg
    source: main
    exclude: 
    - D06
    - D23
    - D36
  - name: 06_DmmyApplWell_SM.cnfg
    source: main
    include: 
    - D06
    - D23
    - D36
```
